apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql123"
            - name: MYSQL_DATABASE
              value: "db_stateputturjob"
            - name: MYSQL_USER
              value: "stateputturjob"
            - name: MYSQL_PASSWORD
              value: "StateputturJob@HitpL2025"
          volumeMounts:
            - name: initdb-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-data-volume
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysql -u root -pmysql123 -e "SELECT 1"
            initialDelaySeconds: 40
            periodSeconds: 10
      volumes:
        - name: initdb-volume
          hostPath:
            path: /root/puttu-X-kubenetes/kubernetes/db_stateputturjob.sql
            type: File
        - name: mysql-data-volume
          hostPath:
            path: /root/puttu-X-kubenetes/kubernetes/mysql/data
            type: DirectoryOrCreate
