apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql123"
            - name: MYSQL_DATABASE
              value: "db_stateputturjob"
            - name: MYSQL_USER
              value: "stateputturjob"
            - name: MYSQL_PASSWORD
              value: "StateputturJob@HitpL2025"
          volumeMounts:
            - name: mysql-data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data-volume
          hostPath:
            path: /root/mysql/data
            type: DirectoryOrCreate